"""Engineering replay of nine frozen descriptive tables, using Python's standard library.

The frozen application_statistics.py is verified then executed with a small numeric
adapter. It is not edited on disk. Bootstrap calls are disabled; the original
paired_bootstrap.csv is integrity checked, never regenerated by this adapter.
This checks accepted-score bookkeeping, not independent scientific validity.
"""
from pathlib import Path
import sys
sys.dont_write_bytecode=True
sys.path.insert(0,str(Path(__file__).resolve().parents[2]/'src'))
from filament_structure.io import Path
import argparse
import csv
import hashlib
import json
import math
import platform
import statistics
import time


def read(path):
    return json.loads(Path(path).read_text(encoding="utf-8-sig"))


def sha(path):
    h = hashlib.sha256()
    with Path(path).open("rb") as f:
        for block in iter(lambda: f.read(1048576), b""):
            h.update(block)
    return h.hexdigest()


class Vector(list):
    def __sub__(self, other):
        assert len(self) == len(other)
        return Vector(a - b for a, b in zip(self, other))

    def __getitem__(self, key):
        if isinstance(key, (list, Vector)):
            assert len(key) == len(self)
            return Vector(x for x, keep in zip(self, key) if keep)
        return super().__getitem__(key)

    def mean(self):
        return statistics.mean(self)

    def sum(self):
        return sum(self)


class Numbers:
    @staticmethod
    def array(values, dtype=None):
        return Vector(dtype(x) if dtype else x for x in values)

    @staticmethod
    def mean(values):
        return statistics.mean(values)

    @staticmethod
    def std(values, ddof=0):
        assert ddof in (0, 1)
        return statistics.stdev(values) if ddof else statistics.pstdev(values)

    isfinite = staticmethod(math.isfinite)


def rows(path):
    with Path(path).open(encoding="utf-8-sig", newline="") as f:
        reader = csv.DictReader(f)
        return reader.fieldnames, list(reader)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--package", default=".", help="Extracted review package root")
    ap.add_argument("--output", required=True, help="New output directory")
    args = ap.parse_args()
    package = Path(args.package).resolve()
    output = Path(args.output).resolve()
    assert not output.exists(), "Use a new output directory; accepted files must not be overwritten"
    started = time.perf_counter()
    fields, members = rows(package / "PACKAGE_FILES_SHA256.csv")
    assert fields == ["path", "bytes", "sha256"]
    for item in members:
        p = (package / item["path"]).resolve()
        assert p.is_relative_to(package) and p.is_file(), item["path"]
        assert p.stat().st_size == int(item["bytes"]) and sha(p) == item["sha256"], item["path"]
    payload = package / "payload"
    source = payload / "project/morphology_application_results_20261002"
    app = payload / "project/manuscript_revision_20261001/morphology_application"
    stage = payload / "project/morphology_application_execution_20261001"
    assert read(source / "COMPLETE.json")["complete"] is True
    signature = read(source / "signature.json")
    lock = read(app / "LOCKED_APPLICATION.json")
    assert sha(app / "LOCKED_APPLICATION.json") == signature["application_lock_sha256"]
    refs = read(app / "REFERENCE_AXES.json")
    assert sha(app / "REFERENCE_AXES.json") == signature["reference_axes_sha256"]
    assert sha(app / "reference_manifest.csv") == signature["reference_manifest_sha256"]
    planned = read(source / "PLANNED_MODE_MATRIX.json")
    assert len(planned) == 42 and sum(x["status"] == "OK" for x in planned) == 39
    expected = read(source / "OUTPUT_SHA256.json")
    required = [p for p in source.rglob("*") if p.is_file() and
                (p.suffix == ".csv" or "receipts" in p.parts)]
    for p in required:
        rel = p.relative_to(source).as_posix()
        assert rel in expected and sha(p) == expected[rel], rel
    receipt_count = 0

    def receipt(path):
        nonlocal receipt_count
        # The original aggregator reads out/receipts. This portable route reads
        # the verified input tree directly rather than duplicating those files.
        rel = Path(path).relative_to(output)
        assert rel.parts[0] == "receipts"
        item = read(source / rel)
        payload_hash = item.pop("payload_sha256")
        actual = hashlib.sha256(json.dumps(item, sort_keys=True, separators=(",", ":")).encode()).hexdigest()
        assert actual == payload_hash, "Corrupt receipt"
        assert item["binding"]["signature"] == signature
        receipt_count += 1
        return item

    src = stage / "application_statistics.py"
    frozen = src.read_text(encoding="utf-8-sig")
    replacements = {
        "import numpy as np\n": "",
        "from mask_acceptance import read\n": "",
        "from frozen_bootstrap import boot\n": "",
        "def read_receipt(p):\n from run_application import load_cached\n return load_cached(p)":
            "def read_receipt(p):\n return receipt_adapter(p)",
        "ci=boot(d[:,None],ids if unit=='observation' else [meta[o]['temporal_group'] for o in ids],seed+71)[:,0] if d is not None else [None,None]":
            "ci=[None,None]  # standard-library route excludes bootstrap output",
    }
    for before, after in replacements.items():
        assert frozen.count(before) == 1, "Unexpected frozen source; refuse adaptation"
        frozen = frozen.replace(before, after)
    ns = {"__file__": str(src), "np": Numbers(), "read": read, "receipt_adapter": receipt}
    exec(compile(frozen, str(src), "exec"), ns)
    frozen_table = ns["table"]

    def table(path, values):
        if Path(path).name != "paired_bootstrap.csv":
            frozen_table(path, values)

    ns["table"] = table
    output.mkdir(parents=True)
    ns["analyze"](output, planned, refs, lock, signature)
    assert receipt_count == 4212
    checks = []
    max_difference = 0.0
    for new in sorted(output.glob("*.csv")):
        old = source / new.name
        old_fields, old_rows = rows(old)
        new_fields, new_rows = rows(new)
        assert old_fields == new_fields and len(old_rows) == len(new_rows), new.name
        table_max = 0.0
        differing_numeric_strings = 0
        for i, (a, b) in enumerate(zip(old_rows, new_rows)):
            for key in old_fields:
                if a[key] == b[key]:
                    continue
                assert a[key] != "" and b[key] != "", (new.name, i, key, "NA changed")
                try:
                    x, y = float(a[key]), float(b[key])
                except ValueError:
                    raise AssertionError((new.name, i, key, "Non-numeric field changed"))
                assert math.isfinite(x) and math.isfinite(y)
                delta = abs(x - y)
                assert delta <= 5e-14, (new.name, i, key, x, y)
                differing_numeric_strings += 1
                table_max = max(table_max, delta)
        max_difference = max(max_difference, table_max)
        checks.append({"file": new.name, "rows": len(new_rows), "fields": len(new_fields),
                       "max_absolute_numeric_difference": table_max,
                       "differing_numeric_strings": differing_numeric_strings,
                       "frozen_sha256": sha(old), "replay_sha256": sha(new),
                       "byte_equal": sha(old) == sha(new)})
    assert len(checks) == 9
    report = {"status": "PASS_NINE_NON_BOOTSTRAP_TABLES_NUMERIC_AND_NA_PARITY",
              "kind": "engineering replay of accepted receipts; not independent scientific validation",
              "python": platform.python_version(), "standard_library_only": True,
              "verified_package_files": len(members), "verified_receipts": receipt_count,
              "frozen_aggregation_source_sha256": sha(src),
              "max_absolute_numeric_difference": max_difference, "tolerance": 5e-14,
              "bootstrap": {"recomputed": False, "verified_original_sha256": sha(source / "paired_bootstrap.csv"),
                            "reason": "Retain original NumPy RNG and frozen 100000-draw algorithm in the separate full-environment route"},
              "elapsed_seconds": time.perf_counter() - started, "tables": checks}
    (output / "REPLAY_QA.json").write_text(json.dumps(report, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({k: report[k] for k in ("status", "verified_receipts", "max_absolute_numeric_difference", "elapsed_seconds")}, indent=2))


if __name__ == "__main__":
    main()
